export const PRODUCTS_CATEGORY_FETCH = "PRODUCTS/CATEGORY_FETCH";
export const PRODUCTS_CATEGORY_FETCH_SUCCESS = "PRODUCTS/CATEGORY_FETCH_SUCCESS";
export const PRODUCTS_CATEGORY_FETCH_FAILED = "PRODUCTS/CATEGORY_FETCH_FAILED";

export const status = {
  LOADING: "LOADING",
  LOADED: "LOADED",
  FAILED: "FAILED"
};
