export const PRODUCTS_PRODUCTS_FETCH = "PRODUCTS/PRODUCTD_FETCH";
export const PRODUCTS_PRODUCTS_FETCH_SUCCESS = "PRODUCTS/PRODUCTD_FETCH_SUCCESS";
export const PRODUCTS_PRODUCTS_FETCH_FAILED = "PRODUCTS/PRODUCTD_FETCH_FAILED";

export const status = {
  LOADING: "LOADING",
  LOADED: "LOADED",
  FAILED: "FAILED"
};